### ISSUE TITLE
How to open dialog or bottomsheet?

### ISSUE THREAD

**Issue by SAGARSURI** [rayliverified/NavigationUtils#2]
Hey @rayliverified 

Is there a possibility to open dialog and bottomsheet? If yes, can you share some example of it. 

Bottomsheet: https://api.flutter.dev/flutter/material/ModalBottomSheetRoute-class.html
Dialog: https://api.flutter.dev/flutter/material/DialogRoute-class.html

**Comment by rayliverified** [comment]
Those are anonymous routes and managed by Flutter's Navigator itself.
Use Flutter Navigator 1 APIs.
