### ISSUE TITLE
[Question] Why is `excludeDeeplinkNavigationPages` part of DeeplinkDestination?

### ISSUE THREAD

**Issue by SAGARSURI** [rayliverified/NavigationUtils#4]
Hey @rayliverified 

Since we want to exclude certain pages from navigation using Deeplink. Don't you think `excludeDeeplinkNavigationPages` should be part of `RouteDelegate` instead of `DeeplinkDestination`?

**Comment by SAGARSURI** [comment]
I misunderstood the usage of this function earlier. Now it's clear. Hence closing it out.

**Comment by rayliverified** [comment]
This is unfortunately a confusing functionality. I don't have a simpler way.

The function `excludeDeeplinkNavigationPages` maps a relational concept on a per page level. Each deeplink can control itself when it's allowed to be navigated to or not.

In my usage, I usually create lists of exclusion pages and add them to the relevant deeplinks.

```dart
List<String> excludeOnboarding = [
  Onboarding1Page.name,
  Onboarding2Page.name,
];

List<String> excludePaymentFlow = [
  CheckoutPage.name,
  PaymentPage.name,
];
```

This prevents distracting deeplinks from taking the user away while they are in a payment flow.

**Comment by rayliverified** [comment]
To exclude navigation at the global level, you can add the exclude pages to the `NavigationDelegate(excludeDeeplinkNavigationPages: [])`.

**Comment by SAGARSURI** [comment]
Thank you so much! This helps a lot 👍🏽
